---
- name: Include setup tasks
  ansible.builtin.include_tasks: setup.yml

- name: Include configuration tasks
  ansible.builtin.include_tasks: configure.yml
  when: influxdb_service_state == "started"
