---
dependency:
  name: galaxy
  enabled: false

driver:
  name: docker

platforms:
  - name: ansible-role-influxdb-debian-11
    image: debian:11
    command: /lib/systemd/systemd
    tmpfs:
      - /run
      - /run/lock
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
  - name: ansible-role-influxdb-debian-12
    image: debian:12
    command: /lib/systemd/systemd
    tmpfs:
      - /run
      - /run/lock
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
  - name: ansible-role-influxdb-ubuntu-2004
    image: ubuntu:20.04
    command: /lib/systemd/systemd
    tmpfs:
      - /run
      - /run/lock
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
  - name: ansible-role-influxdb-ubuntu-2204
    image: ubuntu:22.04
    command: /lib/systemd/systemd
    tmpfs:
      - /run
      - /run/lock
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host

provisioner:
  name: ansible

verifier:
  name: testinfra
  directory: ../default/tests
  env:
    INFLUX_HOST: https://localhost:8086
